[project]
name = "code"
version = "0.1.0"
requires-python = ">=3.13"
dependencies = [
    "datasets>=4.3.0",
    "hydra-core>=1.3.2",
    "tokenizers>=0.22.1",
    "torch>=2.9.0",
    "transformers[torch]>=4.57.1",
]
