[project]
name = "anlp-proj"
version = "0.1.0"
requires-python = ">=3.13"
dependencies = [
    "datasets>=4.4.1",
    "hydra-core>=1.3.2",
    "matplotlib>=3.10.7",
    "seaborn>=0.13.2",
    "torch>=2.9.0",
    "transformers[torch]>=4.57.1",
]
